<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
@include('partials.seo-head')
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Lora:wght@500;600;700&family=Noto+Naskh+Arabic:wght@500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('vendor/remixicon/remixicon.css') }}">
<style>
:root{--navy:#07566a;--deep:#04313d;--cyan:#02add0;--coral:#f66243;--cream:#f8fcfd;--ink:#163a46;--muted:#62777f;--line:#d7e9ed;--serif:'DM Serif Display',serif;--sans:'Plus Jakarta Sans',sans-serif}*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:90px}body{margin:0;background:var(--cream);color:var(--ink);font-family:var(--sans);line-height:1.65}a{color:inherit;text-decoration:none}img{display:block;max-width:100%}.shell{width:min(1180px,calc(100% - 48px));margin:auto}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}
.site-nav{position:fixed;z-index:100;inset:0 0 auto;height:84px;display:flex;align-items:center;justify-content:space-between;padding:0 max(24px,calc((100vw - 1180px)/2));background:rgba(255,255,255,.95);border-bottom:1px solid #dce6ea;backdrop-filter:blur(18px)}.site-nav__brand{display:flex;align-items:center;gap:11px}.site-nav__brand img{width:58px;height:58px;object-fit:contain}.site-nav__brand span{display:grid;line-height:1.08}.site-nav__brand strong{font:1.08rem var(--serif);letter-spacing:.06em;color:var(--navy)}.site-nav__brand small{font-size:.68rem;font-weight:800;color:var(--coral)}.site-nav__links{display:flex;align-items:center;gap:27px;font-size:.78rem;font-weight:800;letter-spacing:.05em;text-transform:uppercase;color:var(--navy)}.site-nav__cta{padding:12px 18px;border-radius:99px;background:var(--cyan);color:#fff}.site-nav__toggle{display:none;width:44px;height:44px;border:0;border-radius:12px;background:var(--navy);color:#fff;font-size:1.4rem}
.hero{position:relative;min-height:760px;padding:156px 0 92px;overflow:hidden;background:linear-gradient(112deg,#07271f,var(--navy) 58%,#176548);color:#fff}.hero:before{content:'';position:absolute;inset:0;opacity:.34;background-image:linear-gradient(30deg,#d8af5718 12%,transparent 12.5%,transparent 87%,#d8af5718 87.5%),linear-gradient(150deg,#d8af5718 12%,transparent 12.5%,transparent 87%,#d8af5718 87.5%),linear-gradient(30deg,#d8af5718 12%,transparent 12.5%,transparent 87%,#d8af5718 87.5%),linear-gradient(150deg,#d8af5718 12%,transparent 12.5%,transparent 87%,#d8af5718 87.5%);background-position:0 0,0 0,36px 63px,36px 63px;background-size:72px 126px}.hero:after{content:'۞';position:absolute;right:-75px;top:20px;color:#d8af5712;font:560px/1 Georgia}.hero__grid{position:relative;z-index:2;display:grid;grid-template-columns:1.12fr .88fr;gap:78px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:9px;color:var(--cyan);font-size:.76rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.eyebrow:before{content:'';width:28px;height:2px;background:currentColor}.hero .eyebrow{color:#e5c778}.hero h1{margin:20px 0 22px;font:clamp(3.3rem,6.1vw,5.8rem)/.99 var(--serif);letter-spacing:-.025em}.hero h1 span{color:#e5c778}.hero__copy{max-width:650px;margin:0 0 34px;color:#dce9e1;font-size:1.06rem}.actions{display:flex;flex-wrap:wrap;gap:12px}.btn{display:inline-flex;min-height:52px;align-items:center;justify-content:center;gap:9px;padding:0 23px;border-radius:99px;font-size:.84rem;font-weight:800;transition:.2s}.btn:hover{transform:translateY(-2px)}.btn--primary{background:var(--coral);color:#193a31;box-shadow:0 13px 30px #8c6b2538}.btn--ghost{border:1px solid #ffffff66}.btn--light{background:#fff;color:var(--navy)}.hero__visual{position:relative}.hero__logo{display:grid;place-items:center;aspect-ratio:4/4.5;padding:42px;border:1px solid #e7cb8d;border-radius:210px 210px 32px 32px;background:linear-gradient(155deg,#fff,#f7f2e5);box-shadow:0 35px 90px #0005}.hero__logo img{width:88%}.hero__badge{position:absolute;right:-22px;bottom:42px;display:flex;align-items:center;gap:11px;width:215px;padding:14px;border-radius:16px;background:#fff;color:var(--ink);box-shadow:0 18px 45px #0004}.hero__badge i{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:#edf7f0;color:var(--cyan);font-size:1.35rem}.hero__badge strong,.hero__badge small{display:block}.hero__badge small{font-size:.67rem;color:var(--muted)}
.quick{position:relative;z-index:3;margin-top:-42px}.quick__grid{display:grid;grid-template-columns:repeat(3,1fr);overflow:hidden;border-radius:22px;background:#fff;box-shadow:0 25px 70px #092f5522}.quick__item{display:flex;gap:16px;padding:26px 28px;border-right:1px solid var(--line)}.quick__item:last-child{border:0}.icon{display:grid;place-items:center;flex:0 0 46px;height:46px;border-radius:14px;background:#e8f9fc;color:var(--cyan);font-size:1.35rem}.quick h3{margin:0;color:var(--navy);font-size:.94rem}.quick p{margin:2px 0 0;color:var(--muted);font-size:.77rem}
.section{padding:105px 0}.white{background:#fff}.soft{background:#edf9fa}.head{display:grid;grid-template-columns:.85fr 1.15fr;gap:55px;align-items:end;margin-bottom:46px}.head h2,.about h2,.cta h2{margin:12px 0 0;font:clamp(2.4rem,4.7vw,4.15rem)/1.05 var(--serif);color:var(--navy)}.head p,.about p{margin:0;color:var(--muted)}.about{display:grid;grid-template-columns:.92fr 1.08fr;gap:72px;align-items:center}.about__visual{position:relative;min-height:500px;overflow:hidden;border-radius:28px;background:linear-gradient(145deg,var(--cyan),var(--navy))}.about__visual:before{content:'اقْرَأْ';position:absolute;inset:0;display:grid;place-items:center;color:#ffffff1c;font:bold 7rem Georgia}.about__visual img{position:absolute;width:62%;left:19%;top:7%;filter:brightness(0) invert(1)}.quote{position:absolute;left:27px;right:27px;bottom:27px;padding:22px;border:1px solid #ffffff44;border-radius:18px;background:#062b4baa;color:#fff;font:1.3rem var(--serif);backdrop-filter:blur(10px)}.checks{display:grid;grid-template-columns:1fr 1fr;gap:11px;margin:27px 0}.checks span{display:flex;align-items:center;gap:8px;font-size:.84rem;font-weight:700}.checks i{color:var(--coral)}
.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card{position:relative;min-height:275px;padding:29px;overflow:hidden;border:1px solid var(--line);border-radius:20px;background:#fff;transition:.25s}.card:hover{transform:translateY(-6px);box-shadow:0 22px 50px #092f5518}.card__num{position:absolute;right:20px;top:2px;color:#edf3f5;font:4.5rem var(--serif)}.card>.icon{position:relative}.card h3{position:relative;margin:23px 0 9px;color:var(--navy);font:1.48rem var(--serif)}.card p{position:relative;margin:0;color:var(--muted);font-size:.84rem}.card a{position:absolute;bottom:24px;color:var(--coral);font-size:.78rem;font-weight:800}
.stats{padding:70px 0;background:var(--navy);color:#fff}.stats__grid{display:grid;grid-template-columns:repeat(4,1fr)}.stat{text-align:center;border-right:1px solid #ffffff2b}.stat:last-child{border:0}.stat strong{display:block;color:#70e1ed;font:3.4rem var(--serif)}.stat span{font-size:.75rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#c8dae6}.gallery{display:grid;grid-template-columns:1.2fr .8fr .8fr;grid-auto-rows:225px;gap:14px}.gallery__item{position:relative;overflow:hidden;border-radius:18px;background:linear-gradient(145deg,#addbe2,#28758b)}.gallery__item:first-child{grid-row:span 2}.gallery__item img{width:100%;height:100%;object-fit:cover}.gallery__item div{height:100%;display:grid;place-items:center;color:#fff;font-size:3rem}.label{position:absolute;left:14px;bottom:14px;padding:8px 12px;border-radius:9px;background:#051f3acc;color:#fff;font-size:.74rem;font-weight:700}.news{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.news__item{overflow:hidden;border:1px solid var(--line);border-radius:20px;background:#fff}.news__media{height:205px;background:linear-gradient(135deg,var(--navy),var(--cyan))}.news__media img{width:100%;height:100%;object-fit:cover}.news__body{padding:23px}.meta{color:var(--coral);font-size:.69rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.news h3{margin:8px 0;color:var(--navy);font:1.35rem/1.2 var(--serif)}.news p{margin:0 0 16px;color:var(--muted);font-size:.82rem}.more{color:var(--cyan);font-size:.77rem;font-weight:800}
.news-more{display:flex;justify-content:center;margin-top:34px}.news-more .btn{min-width:210px}
.cta{position:relative;padding:86px 0;overflow:hidden;background:linear-gradient(105deg,#166246,#0c3c30);color:#fff}.cta:after{content:'﷽';position:absolute;right:4%;top:8%;color:#ffffff0c;font:9rem Georgia}.cta__inner{position:relative;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:45px}.cta h2{max-width:740px;color:#fff}.cta p{max-width:650px;color:#e4eee8}.footer{padding:66px 0 25px;background:var(--deep);color:#cadbd1}.footer__grid{display:grid;grid-template-columns:1.45fr .7fr 1fr;gap:58px}.footer__brand{display:flex;align-items:center;gap:14px;color:#fff}.footer__brand img{width:68px;height:68px;object-fit:contain;padding:4px;border-radius:50%;background:#fff}.footer h3{margin:0 0 15px;color:#fff;font:1.2rem var(--serif)}.footer p,.footer a{font-size:.8rem}.footer a:hover{color:#e5c778}.footer__links{display:grid;gap:8px}.bottom{display:flex;justify-content:space-between;margin-top:45px;padding-top:20px;border-top:1px solid #ffffff20;font-size:.73rem}.reveal{opacity:0;transform:translateY(18px);transition:.6s}.reveal.on{opacity:1;transform:none}
.welcome{display:grid;grid-template-columns:.76fr 1.24fr;gap:72px;align-items:center}.welcome__portrait{position:relative;min-height:510px;overflow:hidden;border-radius:28px 28px 120px 28px;background:linear-gradient(150deg,#dff7fa,#8ed9e5)}.welcome__portrait:after{content:'';position:absolute;inset:auto -80px -120px auto;width:300px;height:300px;border:65px solid #ffffff55;border-radius:50%}.welcome__portrait img{position:absolute;z-index:1;width:100%;height:100%;object-fit:cover;object-position:center top}.welcome__placeholder{position:absolute;inset:0;display:grid;place-items:center;color:#fff;font-size:10rem}.welcome__placeholder i{filter:drop-shadow(0 18px 30px #082f5533)}.welcome__mark{position:absolute;z-index:2;right:22px;bottom:22px;width:78px;height:78px;display:grid;place-items:center;border-radius:50%;background:var(--coral);color:#fff;font:3.2rem var(--serif);box-shadow:0 16px 35px #082f5533}.welcome__copy h2{margin:13px 0 22px;font:clamp(2.4rem,4.7vw,4.15rem)/1.05 var(--serif);color:var(--navy)}.welcome__copy blockquote{margin:0;color:var(--muted);font:1.13rem/1.85 var(--serif)}.welcome__copy blockquote p{margin:0 0 16px}.welcome__signature{display:flex;align-items:center;gap:13px;margin-top:28px;padding-top:23px;border-top:1px solid var(--line)}.welcome__signature span{width:36px;height:2px;background:var(--coral)}.welcome__signature strong,.welcome__signature small{display:block}.welcome__signature strong{color:var(--navy)}.welcome__signature small{color:var(--muted);font-size:.75rem}
@media(max-width:900px){.site-nav__links{position:absolute;top:75px;left:16px;right:16px;display:none;padding:16px;border-radius:18px;background:#fff;box-shadow:0 20px 50px #051f3a33}.site-nav.is-open .site-nav__links{display:grid;gap:3px}.site-nav__links a{padding:10px}.site-nav__toggle{display:block}.hero__grid,.about,.welcome,.head{grid-template-columns:1fr}.hero__grid{gap:45px}.hero__visual{max-width:500px}.welcome__portrait{max-width:560px;width:100%}.quick__grid{grid-template-columns:1fr}.quick__item{border-right:0;border-bottom:1px solid var(--line)}.cards,.news{grid-template-columns:repeat(2,1fr)}.stats__grid{grid-template-columns:repeat(2,1fr);gap:30px}.stat:nth-child(2){border:0}.gallery{grid-template-columns:1fr 1fr}.gallery__item:first-child{grid-row:auto}.cta__inner{display:block}.cta .btn{margin-top:22px}.footer__grid{grid-template-columns:1fr 1fr}.footer__grid>:first-child{grid-column:1/-1}}@media(max-width:600px){.shell{width:calc(100% - 30px)}.site-nav{height:74px;padding:0 15px}.site-nav__brand img{width:48px;height:48px}.hero{min-height:auto;padding:124px 0 90px}.hero h1{font-size:3rem}.hero__visual{width:92%;margin:auto}.hero__badge{right:-10px}.section{padding:76px 0}.welcome__portrait{min-height:430px}.welcome__placeholder{font-size:7rem}.cards,.news,.gallery{grid-template-columns:1fr}.gallery{grid-auto-rows:240px}.checks{grid-template-columns:1fr}.footer__grid{grid-template-columns:1fr}.footer__grid>:first-child{grid-column:auto}.bottom{display:block}}@media(prefers-reduced-motion:reduce){.reveal{opacity:1;transform:none;transition:none}}
.hero h1{max-width:720px;font-size:clamp(2.25rem,3.9vw,3.7rem);line-height:1.12;letter-spacing:-.025em}@media(max-width:600px){.hero h1{font-size:2rem;line-height:1.16}.hero__copy{font-size:.96rem}}
:root{--serif:'Lora',Georgia,serif;--sans:'Plus Jakarta Sans',Arial,sans-serif;--arabic:'Noto Naskh Arabic','Traditional Arabic',serif}.hero h1,.head h2,.about h2,.welcome__copy h2,.cta h2{font-weight:600}.head h2,.about h2,.welcome__copy h2,.cta h2{letter-spacing:-.018em}.card h3,.news h3,.identity-card h3,.site-nav__brand strong{font-weight:600}.hero:after{font-family:var(--arabic)}.about__visual:before{font-family:var(--arabic)}.cta:after{font-family:var(--arabic)}
.site-nav{background:transparent;border-bottom-color:transparent;transition:background .3s ease,border-color .3s ease,box-shadow .3s ease,transform .3s ease}.site-nav:not(.is-scrolled) .site-nav__brand strong,.site-nav:not(.is-scrolled) .site-nav__links>a:not(.site-nav__cta){color:#fff;text-shadow:0 1px 12px #061e1899}.site-nav:not(.is-scrolled) .site-nav__brand small{color:#e5c778}.site-nav:not(.is-scrolled) .site-nav__cta{background:#d8af57;color:#183a31}.site-nav:not(.is-scrolled) .site-nav__toggle{border:1px solid #ffffff55;background:#ffffff18}.site-nav.is-scrolled{background:rgba(255,255,255,.96);border-bottom-color:var(--line);box-shadow:0 10px 35px #082a2214}.site-nav.is-scrolled .site-nav__cta{background:var(--cyan);color:#fff}@media(max-width:900px){.site-nav:not(.is-scrolled).is-open{background:rgba(255,255,255,.98);box-shadow:0 16px 40px #082a2226}.site-nav:not(.is-scrolled).is-open .site-nav__brand strong{color:var(--navy);text-shadow:none}.site-nav:not(.is-scrolled).is-open .site-nav__toggle{background:var(--navy)}.site-nav:not(.is-scrolled) .site-nav__links>a:not(.site-nav__cta){color:var(--navy);text-shadow:none}}
body .site-nav{background:rgba(255,255,255,var(--nav-bg-alpha,0));border-bottom-color:rgba(22,133,91,var(--nav-border-alpha,0));box-shadow:0 10px 35px rgba(8,42,34,var(--nav-shadow-alpha,0));transition:none}body .site-nav .site-nav__brand strong,body .site-nav .site-nav__links>a:not(.site-nav__cta){color:var(--nav-text-color,#fff);text-shadow:0 1px 12px rgba(6,30,24,var(--nav-text-shadow,.6))}body .site-nav .site-nav__brand small{color:var(--nav-accent-color,#e5c778)}body .site-nav .site-nav__cta{background:var(--nav-cta-bg,#d8af57);color:var(--nav-cta-text,#183a31)}body .site-nav .site-nav__toggle{border:1px solid rgba(255,255,255,var(--nav-toggle-border,.34));background:var(--nav-toggle-bg,rgba(255,255,255,.09))}@media(max-width:900px){body .site-nav.is-open{background:rgba(255,255,255,.98);box-shadow:0 16px 40px rgba(8,42,34,.15)}body .site-nav.is-open .site-nav__brand strong{color:var(--navy);text-shadow:none}body .site-nav.is-open .site-nav__brand small{color:#a77d28}body .site-nav.is-open .site-nav__toggle{background:var(--navy)}body .site-nav .site-nav__links>a:not(.site-nav__cta){color:var(--navy);text-shadow:none}}
.quick{margin-top:-54px;padding-bottom:20px}.quick__grid{position:relative;gap:14px;overflow:visible;border-radius:0;background:transparent;box-shadow:none}.quick__grid:before{content:'۞';position:absolute;z-index:2;left:50%;top:-16px;display:grid;width:34px;height:34px;place-items:center;border:0;border-radius:50%;background:var(--coral);color:var(--navy);font:600 1rem var(--arabic);transform:translateX(-50%);box-shadow:0 8px 20px #082a2220}.quick__item{position:relative;min-height:128px;align-items:center;gap:18px;padding:27px 25px;overflow:hidden;border:0;border-radius:18px;background:linear-gradient(145deg,#fff 25%,#f7fbf8);box-shadow:0 18px 45px #082a2212;transition:transform .25s ease,box-shadow .25s ease}.quick__item:before{content:'';position:absolute;inset:0;background-image:linear-gradient(145deg,#fffefef5 20%,#f7fbf8e8),url('https://commons.wikimedia.org/wiki/Special:Redirect/file/Geometric%20Pattern.svg?width=512');background-position:center,right center;background-repeat:no-repeat;background-size:cover,210px;opacity:.32}.quick__item:after{content:'۞';position:absolute;right:-13px;bottom:-29px;color:#16855b0a;font:82px/1 var(--arabic)}.quick__item:last-child{border:0}.quick__item:hover{transform:translateY(-5px);box-shadow:0 24px 55px #082a2220}.quick__item .icon{position:relative;z-index:1;width:52px;height:58px;flex-basis:52px;border:0;border-radius:26px 26px 13px 13px;background:linear-gradient(160deg,#edf8f2,#e2f3ec);color:#16855b;font-size:1.45rem;box-shadow:inset 0 0 0 5px #ffffff80}.quick__item:nth-child(2) .icon{background:linear-gradient(160deg,#fff8e8,#f5e9c9);color:#a77d28}.quick h3{position:relative;z-index:1;margin-bottom:4px;font:600 1.02rem/1.35 var(--serif);color:var(--navy)}.quick p{position:relative;z-index:1;max-width:260px;font-size:.78rem;line-height:1.65}@media(max-width:900px){.quick{margin-top:-34px}.quick__grid{gap:10px}.quick__grid:before{display:none}.quick__item,.quick__item:last-child{min-height:auto;border:0;padding:22px}}@media(max-width:600px){.quick{padding-bottom:4px}.quick__item{border-radius:16px}.quick__item .icon{width:48px;height:52px;flex-basis:48px}}
.quick__grid{gap:0;overflow:hidden;border:1px solid #dce8e1;border-radius:22px;background:linear-gradient(145deg,#fff 25%,#f7fbf8);box-shadow:0 20px 55px #082a2215}
.quick__grid:after{content:'';position:absolute;inset:0;pointer-events:none;background:url('{{ asset('assets/islamic-pattern-gold.jpg') }}') center/620px auto repeat;opacity:.12}
.quick__grid:before{display:none}
.quick__item,.quick__item:last-child{min-height:118px;border:0;border-right:1px solid #dce8e1;border-radius:0;background:transparent;box-shadow:none}
.quick__item:last-child{border-right:0}
.quick__item:before,.quick__item:after{display:none}
.quick__item:hover{transform:none;background:#ffffff73;box-shadow:none}
@media(max-width:900px){.quick__grid{gap:0}.quick__item,.quick__item:last-child{border:0;border-bottom:1px solid #dce8e1;border-radius:0;background:transparent}.quick__item:last-child{border-bottom:0}}
.program-section{position:relative;padding:72px 0;overflow:hidden}.program-section .head{margin-bottom:28px;align-items:center}.program-section .head h2{font-size:clamp(2.15rem,4vw,3.45rem)}.program-section .cards{gap:15px}.program-section .card{min-height:245px;padding:25px 24px;border-color:#d9e6df;border-radius:18px;background:linear-gradient(145deg,#fff 35%,#f7fbf8);box-shadow:0 14px 35px #082a220b}.program-section .card:before{content:'';position:absolute;z-index:0;inset:0;background:url('{{ asset('assets/islamic-pattern-gold.jpg') }}') center/390px auto repeat;opacity:.16;pointer-events:none}.program-section .card:after{content:'۞';position:absolute;right:21px;bottom:16px;color:#16855b10;font:42px/1 var(--arabic)}.program-section .card__num{z-index:1;right:18px;top:5px;color:#16855b0d;font-size:4rem}.program-section .card>.icon,.program-section .card h3,.program-section .card p,.program-section .card a{z-index:1}.program-section .card>.icon{width:50px;height:56px;border-radius:25px 25px 12px 12px;background:linear-gradient(160deg,#edf8f2,#dff1e8);color:#16855b;box-shadow:inset 0 0 0 1px #16855b12}.program-section .card:nth-child(even)>.icon{background:linear-gradient(160deg,#fff8e8,#f3e5bf);color:#a77d28}.program-section .card h3{margin:18px 0 7px;font-size:1.35rem}.program-section .card p{line-height:1.65}.program-section .card a{bottom:20px;color:#16855b}.program-section .card:hover{border-color:#d8af576b;box-shadow:0 20px 45px #082a2217}.program-section .card:hover>.icon{transform:translateY(-2px)}
@media(max-width:900px){.program-section{padding:58px 0}.program-section .head{margin-bottom:23px}.program-section .cards{gap:13px}}@media(max-width:600px){.program-section{padding:48px 0}.program-section .card{min-height:225px;padding:22px}.program-section .card a{bottom:18px}}
.hero{background:linear-gradient(112deg,#04313d,var(--navy) 58%,#078aa6)}.hero:before{background-image:linear-gradient(30deg,#02add01c 12%,transparent 12.5%,transparent 87%,#02add01c 87.5%),linear-gradient(150deg,#f662431c 12%,transparent 12.5%,transparent 87%,#f662431c 87.5%),linear-gradient(30deg,#02add01c 12%,transparent 12.5%,transparent 87%,#02add01c 87.5%),linear-gradient(150deg,#f662431c 12%,transparent 12.5%,transparent 87%,#f662431c 87.5%)}.hero:after{color:#f6624315}.hero .eyebrow,.hero h1 span{color:#ff8067}.hero__copy{color:#d9f3f7}.hero__logo{border-color:#91dce9;background:linear-gradient(155deg,#fff,#effafd)}.hero__badge i{background:#e5f8fc;color:var(--cyan)}.btn--primary{color:#fff;box-shadow:0 13px 30px #f6624338}.soft{background:#edf9fb}.about__visual{background:linear-gradient(145deg,var(--cyan),var(--navy))}.quote{background:#06475dcc}.stats{background:var(--navy)}.stat strong{color:#56d4ec}.stat span{color:#d3edf2}.gallery__item{background:linear-gradient(145deg,#7bd7e8,#087d98)}.cta{background:linear-gradient(105deg,#087d98,#06475b)}.cta p{color:#d9f3f7}.footer{background:var(--deep);color:#cce5ea}.footer a:hover{color:var(--coral)}.quick__grid{border-color:#d4e8ec}.quick__item,.quick__item:last-child{border-color:#d4e8ec}.quick__item .icon{background:linear-gradient(160deg,#e8f9fc,#d9f4f9);color:var(--cyan)}.quick__item:nth-child(2) .icon{background:linear-gradient(160deg,#fff2ef,#ffe1da);color:var(--coral)}.program-section .card{border-color:#d4e8ec;background:linear-gradient(145deg,#fff 35%,#f2fbfc)}.program-section .card:after{color:#02add014}.program-section .card__num{color:#02add014}.program-section .card>.icon{background:linear-gradient(160deg,#e8f9fc,#d9f4f9);color:var(--cyan)}.program-section .card:nth-child(even)>.icon{background:linear-gradient(160deg,#fff2ef,#ffe1da);color:var(--coral)}.program-section .card a{color:var(--cyan)}.program-section .card:hover{border-color:#f6624370}.welcome__portrait{background:linear-gradient(150deg,#e5f8fc,#85dbea)}
body .site-nav{border-bottom-color:rgba(2,173,208,var(--nav-border-alpha,0));box-shadow:0 10px 35px rgba(4,49,61,var(--nav-shadow-alpha,0))}body .site-nav .site-nav__brand small{color:var(--nav-accent-color,var(--coral))}body .site-nav .site-nav__cta{background:var(--nav-cta-bg,var(--coral))!important;color:#fff!important}@media(max-width:900px){body .site-nav.is-open .site-nav__brand small{color:var(--coral)}}.cta .eyebrow{color:#ff8067!important}
.about__paragraphs{display:grid;gap:12px}.about__paragraphs p{margin:0}.about__paragraphs p:not(:first-child){font-size:.94rem;line-height:1.75}
/* Skala heading section yang lebih tenang dan proporsional. */
.head h2,.about h2,.welcome__copy h2,.cta h2{font-size:clamp(1.9rem,3.3vw,3.15rem);line-height:1.1}
.program-section .head h2{font-size:clamp(1.9rem,3vw,2.85rem)}
@media(max-width:600px){.head h2,.about h2,.welcome__copy h2,.cta h2,.program-section .head h2{font-size:1.85rem;line-height:1.15}}
/* Scroll motion: reveal sekali, stagger ringan, dan tetap responsif. */
:root{--motion-duration:720ms;--motion-ease:cubic-bezier(.22,1,.36,1);--motion-distance:34px}
main>section{scroll-margin-top:84px}
.reveal{opacity:1;transform:none;filter:none}
html.motion-ready .reveal{--reveal-x:0px;--reveal-y:var(--motion-distance);opacity:0;transform:translate3d(var(--reveal-x),var(--reveal-y),0) scale(.985);filter:blur(7px);will-change:opacity,transform,filter}
html.motion-ready .reveal[data-reveal="left"]{--reveal-x:calc(var(--motion-distance) * -1);--reveal-y:0px}
html.motion-ready .reveal[data-reveal="right"]{--reveal-x:var(--motion-distance);--reveal-y:0px}
html.motion-ready .reveal[data-reveal="scale"]{--reveal-x:0px;--reveal-y:14px;transform:translate3d(0,14px,0) scale(.94)}
html.motion-ready .reveal.on{animation:pondok-reveal var(--motion-duration) var(--motion-ease) var(--reveal-delay,0ms) forwards}
@keyframes pondok-reveal{to{opacity:1;transform:translate3d(0,0,0) scale(1);filter:blur(0)}}
@media(max-width:600px){:root{--motion-duration:600ms;--motion-distance:22px}html.motion-ready .reveal{filter:blur(4px)}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal,html.motion-ready .reveal,html.motion-ready .reveal.on{opacity:1!important;transform:none!important;filter:none!important;animation:none!important;transition:none!important}}
/* Ornamen Islami kontemporer: pola tenang, divider arabesque, dan detail mihrab. */
.section{position:relative;isolation:isolate;overflow:hidden}.section:before{content:'';position:absolute;z-index:-1;inset:0;pointer-events:none;background-image:linear-gradient(90deg,rgba(255,255,255,.9),rgba(255,255,255,.55) 22%,rgba(255,255,255,.55) 78%,rgba(255,255,255,.9)),url('{{ asset('assets/islamic-pattern-gold.jpg') }}');background-position:center,center;background-size:auto,560px auto;background-repeat:no-repeat,repeat;opacity:.11}.section.soft:before{background-image:linear-gradient(90deg,rgba(237,249,251,.96),rgba(237,249,251,.67) 24%,rgba(237,249,251,.67) 76%,rgba(237,249,251,.96)),url('{{ asset('assets/islamic-pattern-gold.jpg') }}');opacity:.16}.section>.shell{position:relative;z-index:1}.section>.shell:before{content:'۞';position:absolute;left:50%;top:-68px;display:grid;width:37px;height:37px;place-items:center;border:1px solid rgba(2,173,208,.28);border-radius:50%;background:var(--cream);color:var(--coral);font:600 1.05rem/1 var(--arabic);transform:translateX(-50%) rotate(45deg);box-shadow:0 0 0 7px rgba(255,255,255,.75)}.section>.shell:after{content:'';position:absolute;left:50%;top:-50px;width:min(290px,34vw);height:1px;background:linear-gradient(90deg,transparent,var(--cyan),transparent);transform:translateX(-50%);opacity:.38}.section>.shell:before{z-index:2}.section>.shell>*{position:relative;z-index:1}
.head .eyebrow,.about .eyebrow,.welcome .eyebrow{position:relative;padding-left:43px}.head .eyebrow:before,.about .eyebrow:before,.welcome .eyebrow:before{position:absolute;left:0}.head .eyebrow:after,.about .eyebrow:after,.welcome .eyebrow:after{content:'◆';margin-left:3px;color:var(--coral);font-size:.52rem}
.identity-card,.news__item{position:relative;overflow:hidden}.identity-card:before,.news__item:after{content:'۞';position:absolute;right:-15px;bottom:-24px;color:rgba(2,173,208,.07);font:74px/1 var(--arabic);pointer-events:none}.identity-card:after{content:'';position:absolute;left:0;top:0;width:100%;height:3px;background:linear-gradient(90deg,var(--cyan),var(--coral),transparent 82%)}.identity-card i{position:relative;display:grid;width:46px;height:52px;place-items:center;border-radius:25px 25px 10px 10px;background:linear-gradient(160deg,#e8f9fc,#fff2ef);box-shadow:inset 0 0 0 1px rgba(2,173,208,.13)}
.identity-vision,.ppdb-panel{position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.14);border-radius:90px 90px 22px 22px}.identity-vision:after,.ppdb-panel:after{content:'۞';position:absolute;right:-22px;bottom:-34px;color:rgba(255,255,255,.065);font:112px/1 var(--arabic)}.identity-mission li{overflow:hidden}.identity-mission li:after{content:'';position:absolute;inset:0 0 0 auto;width:54px;background:url('{{ asset('assets/islamic-pattern-gold.jpg') }}') center/180px auto;opacity:.09}
.hero{isolation:isolate;background:radial-gradient(circle at 82% 28%,rgba(2,173,208,.3),transparent 32%),radial-gradient(circle at 8% 82%,rgba(246,98,67,.1),transparent 27%),linear-gradient(118deg,#032d38 0%,#07566a 57%,#087f98 100%)}.hero:before{z-index:0;opacity:.34;background-image:radial-gradient(circle at 76% 30%,rgba(127,231,242,.17),transparent 32%),url('{{ asset('assets/islamic-pattern-hero.png') }}');background-position:center,center -34px;background-size:auto,720px auto;background-repeat:no-repeat,repeat;mask-image:radial-gradient(ellipse 96% 72% at 50% 5%,rgba(0,0,0,.96) 10%,rgba(0,0,0,.62) 55%,transparent 100%);-webkit-mask-image:radial-gradient(ellipse 96% 72% at 50% 5%,rgba(0,0,0,.96) 10%,rgba(0,0,0,.62) 55%,transparent 100%)}.hero:after{z-index:0;right:-105px;top:-26px;color:rgba(98,220,234,.055);font-size:640px;transform:rotate(8deg)}
.hero__grid>div:first-child{transform:translateY(-28px)}
.about__visual:before{z-index:1;background:linear-gradient(180deg,rgba(3,45,56,.02) 42%,rgba(3,45,56,.78) 100%);color:transparent;pointer-events:none}.about__visual .about__image{inset:0;width:100%;height:100%;object-fit:cover;object-position:center center;filter:none;transform:scale(1.01)}.about__visual .quote{z-index:2}
.hero__photo{position:relative;aspect-ratio:4/4.7;overflow:hidden;border:1px solid rgba(145,220,233,.8);border-radius:210px 210px 34px 34px;background:#07566a;box-shadow:0 35px 90px rgba(0,0,0,.38)}.hero__photo:before{content:'';position:absolute;z-index:1;inset:0;background:linear-gradient(180deg,rgba(4,49,61,.04) 48%,rgba(4,49,61,.68) 100%);pointer-events:none}.hero__photo:after{content:'';position:absolute;z-index:2;inset:14px;border:1px solid rgba(255,255,255,.3);border-radius:196px 196px 25px 25px;pointer-events:none}.hero__photo>img{width:100%;height:100%;object-fit:cover;object-position:center 58%;transform:scale(1.015)}.hero__seal{position:absolute;z-index:3;left:28px;bottom:27px;display:grid;width:76px;height:76px;place-items:center;padding:9px;border:1px solid rgba(255,255,255,.75);border-radius:50%;background:rgba(255,255,255,.94);box-shadow:0 14px 34px rgba(0,0,0,.25);backdrop-filter:blur(8px)}.hero__seal img{width:100%;height:100%;object-fit:contain}.hero__photo-caption{position:absolute;z-index:3;left:122px;right:28px;bottom:31px;color:#fff}.hero__photo-caption strong,.hero__photo-caption span{display:block}.hero__photo-caption strong{font:600 1.03rem/1.3 var(--serif)}.hero__photo-caption span{margin-top:2px;color:#d9f3f7;font-size:.7rem;letter-spacing:.05em;text-transform:uppercase}.hero__visual>.hero__badge{top:54px;right:-22px;bottom:auto}
.footer{position:relative;border-top:1px solid rgba(255,255,255,.16)}.footer:before{content:'';position:absolute;inset:0 0 auto;height:2px;background:linear-gradient(90deg,transparent 4%,rgba(86,212,236,.72) 28%,rgba(246,98,67,.68) 50%,rgba(86,212,236,.72) 72%,transparent 96%);opacity:.8}
@media(max-width:900px){.section>.shell:before{top:-55px}.section>.shell:after{top:-37px;width:42vw}.identity-vision,.ppdb-panel{border-radius:58px 58px 20px 20px}}
@media(max-width:600px){.section:before{background-size:auto,390px auto}.section>.shell:before{top:-47px;width:31px;height:31px}.section>.shell:after{top:-32px;width:48vw}.hero__grid>div:first-child{transform:none}.hero__photo{border-radius:150px 150px 26px 26px}.hero__photo:after{inset:10px;border-radius:140px 140px 19px 19px}.hero__seal{left:18px;bottom:18px;width:62px;height:62px}.hero__photo-caption{left:92px;right:18px;bottom:21px}.hero__photo-caption strong{font-size:.88rem}.hero__photo-caption span{font-size:.6rem}.hero__visual>.hero__badge{top:34px;right:-10px;transform:scale(.86);transform-origin:top right}.identity-card i{width:42px;height:48px}.identity-vision,.ppdb-panel{border-radius:42px 42px 18px 18px}}
</style></head>
@php
$fallback='Pondok Pesantren Tahfidzul Qur’an Al-Madinah Al-Kamilah';$displayName=str_contains(strtolower((string)($brandName??'')),'bubba')?$fallback:($brandName?:$fallback);$logo=asset('logo/al-madinatul-kamilah.png');$aboutText=$about['story']['content'][0]['text']??$websiteDescription??'Pondok pesantren yang berfokus pada pembentukan generasi penghafal Al-Qur’an yang berilmu, beradab, mandiri, dan bermanfaat bagi umat.';$phone=$contact['phones'][0]??['number'=>'+6287831633012','displayNumber'=>'+62 878-3163-3012','whatsappUrl'=>'https://wa.me/6287831633012'];$email=$contact['emails'][0]['email']??null;$address=$contact['address']['fullAddress']??'Informasi alamat pondok akan segera diperbarui.';$wa='https://wa.me/6287831633012?text='.rawurlencode("Assalamu'alaikum, saya ingin bertanya mengenai Pondok Pesantren Al-Madinah Al-Kamilah.");$legacyHeroPattern='/\b(homecare|pijat|bubba|pregnancy|postnatal|newborn|bayi|ibu hamil|bdn\.)\b/i';$heroDescription=trim((string)($hero['description']??''));$heroPart1=trim((string)($hero['heading']['part1']??''));$heroPart2=trim((string)($hero['heading']['part2']??''));$heroEyebrow=trim((string)($hero['badge']['text']??''));if($heroDescription===''||preg_match($legacyHeroPattern,$heroDescription))$heroDescription='Pendidikan tahfidz yang memadukan hafalan Al-Qur’an, pemahaman agama, adab, dan kemandirian dalam lingkungan pondok yang hangat.';if($heroPart1===''||preg_match($legacyHeroPattern,$heroPart1))$heroPart1='Dekat dengan Al-Qur’an';if($heroPart2===''||preg_match($legacyHeroPattern,$heroPart2))$heroPart2='Mulia dalam Kehidupan.';if($heroEyebrow===''||preg_match($legacyHeroPattern,$heroEyebrow))$heroEyebrow='Mencetak Generasi Qur’ani';$heroButtons=array_slice(is_array($hero['buttons']??null)?$hero['buttons']:[],0,2);$safeHeroLink=static function($url,$fallbackLink)use($wa){$url=trim((string)$url);if($url==='#contact')return $wa;if(str_starts_with($url,'#')||str_starts_with($url,'/')||preg_match('/^https?:\/\//i',$url))return $url;return $fallbackLink;};
$ppdbMessage="Assalamu'alaikum, saya ingin mendapatkan informasi PPDB Pondok Pesantren Al-Madinah Al-Kamilah.\n\nFORM MINAT PPDB\nNama calon santri: \nUsia: \nJenjang/program yang diminati: \nAsal sekolah: \nDomisili: \nNama orang tua/wali: \nNomor WhatsApp wali: \nPertanyaan/keterangan: \n\nMohon informasi mengenai persyaratan, jadwal, biaya, dan ketersediaan kuota. Terima kasih.";
$waPpdb='https://wa.me/6287831633012?text='.rawurlencode($ppdbMessage);
$fallbackPrograms=[['Tahfidz Al-Qur’an','Program hafalan terarah dengan target, murajaah, dan pendampingan intensif.','ri-book-open-line'],['Tahsin & Tilawah','Memperbaiki makhraj, tajwid, dan kefasihan bacaan secara berkelanjutan.','ri-mic-line'],['Adab & Diniyah','Pembinaan akidah, ibadah, akhlak, dan kebiasaan islami santri.','ri-moon-clear-line'],['Bahasa & Akademik','Penguatan bahasa Arab, wawasan keislaman, dan kompetensi akademik.','ri-graduation-cap-line'],['Kemandirian Santri','Membangun disiplin, tanggung jawab, kepemimpinan, dan kecakapan hidup.','ri-seedling-line'],['Pembinaan Karakter','Menumbuhkan pribadi Qur’ani yang santun, tangguh, dan peduli.','ri-heart-3-line']];
@endphp
@php
$heroMascotSource = trim((string) data_get($hero, 'layout.mascot.image', ''));
$heroBackgroundSource = trim((string) data_get($hero, 'background.image', ''));
$heroImageSource = $heroMascotSource !== '' ? $heroMascotSource : $heroBackgroundSource;
$heroPanelImage = $heroImageSource !== '' ? $mediaUrl($heroImageSource) : null;
$normalizedHeroImageSource = strtolower($heroImageSource);
if (!$heroPanelImage || preg_match($legacyHeroPattern, $heroImageSource) || str_contains($normalizedHeroImageSource, 'logo') || str_contains($normalizedHeroImageSource, 'al-madinah-al-kamilah')) {
    $heroPanelImage = asset('assets/hero-santri.jpg');
}
$allowedHeroAlignments = ['top', 'center', 'bottom'];
$heroImageAlignment = strtolower(trim((string) data_get($hero, 'layout.mascot.alignment', 'center')));
$heroImageAlignment = in_array($heroImageAlignment, $allowedHeroAlignments, true) ? $heroImageAlignment : 'center';
$heroStatLabels = collect($hero['stats'] ?? [])->pluck('label')->filter()->take(3)->values()->all();
$heroPanelTitle = $heroPart2 !== '' ? $heroPart2 : $displayName;
$heroPanelMeta = !empty($heroStatLabels) ? implode(' • ', $heroStatLabels) : 'Ilmu • Adab • Kebersamaan';
$heroFloatingTitle = $heroEyebrow !== '' ? $heroEyebrow : 'Pendidikan Terpadu';
$heroFloatingMeta = !empty($heroStatLabels) ? implode(' • ', array_slice($heroStatLabels, 0, 2)) : 'Qur’an • Ilmu • Adab';

$aboutParagraphs = collect($about['story']['content'] ?? [])
    ->map(fn ($item) => trim((string) ($item['text'] ?? '')))
    ->filter()
    ->values()
    ->all();
if (empty($aboutParagraphs)) {
    $aboutParagraphs = [$aboutText];
}
$aboutImageSource = trim((string) data_get($about, 'story.image.url', ''));
$aboutImage = $aboutImageSource !== '' ? $mediaUrl($aboutImageSource) : asset('assets/tentang-pondok-santri.jpg');
$aboutImageAlt = trim((string) data_get($about, 'story.image.alt', '')) ?: 'Kegiatan santri Pondok Pesantren Tahfidzul Qur’an Al-Madinah Al-Kamilah';
$aboutQuote = trim((string) data_get($about, 'story.image.caption', '')) ?: trim((string) data_get($about, 'story.image.description', '')) ?: 'Sebaik-baik kalian adalah yang mempelajari Al-Qur’an dan mengajarkannya.';
$aboutBadge = trim((string) data_get($about, 'story.badge', '')) ?: 'Tentang Pondok';
$aboutTitle = trim((string) data_get($about, 'story.title', '')) ?: 'Menumbuhkan Huffazh yang Berilmu dan Berakhlak.';
$aboutHighlights = collect(data_get($about, 'story.highlights', []))->filter(fn ($item) => trim((string) ($item['text'] ?? '')) !== '')->values()->all();
$defaultHighlights = [
    ['text' => 'Kurikulum Tahfidz', 'description' => 'Target hafalan dan murajaah konsisten.', 'color' => 'ri-book-2-line'],
    ['text' => 'Asatidz Pembimbing', 'description' => 'Pendampingan dekat dalam belajar dan beradab.', 'color' => 'ri-parent-line'],
    ['text' => 'Lingkungan Islami', 'description' => 'Suasana nyaman untuk tumbuh bersama Al-Qur’an.', 'color' => 'ri-home-heart-line'],
    ['text' => 'Pembiasaan Ibadah', 'description' => 'Ibadah dan adab dibangun dalam keseharian.', 'color' => 'ri-moon-clear-line'],
];
if (empty($aboutHighlights)) $aboutHighlights = $defaultHighlights;
$quickHighlights = array_slice($aboutHighlights, 0, 3);
$aboutCta = $about['callToAction'] ?? [];
$ctaButtons = array_slice(is_array($aboutCta['buttons'] ?? null) ? $aboutCta['buttons'] : [], 0, 2);
$programIntro = trim((string) data_get($about, 'companyInfo.missionStatement', '')) ?: 'Program disusun untuk menjaga keseimbangan kualitas hafalan, pemahaman agama, akademik, adab, dan kecakapan hidup santri.';
@endphp
<body>@include('partials.landing-navbar',['brandName'=>$displayName,'whatsappUrl'=>$wa])<main>
<section class="hero" id="home"><div class="shell hero__grid"><div><span class="eyebrow">{{ $heroEyebrow }}</span><h1>{{ $heroPart1 }}, <span>{{ $heroPart2 }}</span></h1><p class="hero__copy">{{ $heroDescription }}</p><div class="actions">@forelse($heroButtons as $i=>$button)@php $heroHref=$safeHeroLink($button['link']??null,$i===0?'#program':$wa); @endphp<a class="btn {{ $i===0?'btn--primary':'btn--ghost' }}" href="{{ $heroHref }}" @if(str_starts_with($heroHref,'https://wa.me/')) target="_blank" rel="noopener" @endif>{{ $button['text']??($i===0?'Jelajahi Program':'Informasi Pendaftaran') }} <i class="{{ $button['icon']??($i===0?'ri-arrow-down-line':'ri-customer-service-2-line') }}"></i></a>@empty<a class="btn btn--primary" href="#program">Jelajahi Program <i class="ri-arrow-down-line"></i></a><a class="btn btn--ghost" href="{{ $wa }}" target="_blank" rel="noopener"><i class="ri-whatsapp-line"></i> Informasi Pendaftaran</a>@endforelse</div></div><div class="hero__visual"><div class="hero__photo"><img src="{{ $heroPanelImage }}" alt="{{ $heroPanelTitle }}" style="object-position:center {{ $heroImageAlignment }}"><span class="hero__seal"><img src="{{ $logo }}" alt=""></span><span class="hero__photo-caption"><strong>{{ $heroPanelTitle }}</strong><span>{{ $heroPanelMeta }}</span></span></div><div class="hero__badge"><i class="ri-shield-check-line"></i><span><strong>{{ $heroFloatingTitle }}</strong><small>{{ $heroFloatingMeta }}</small></span></div></div></div></section>
<div class="quick"><div class="shell quick__grid">@foreach($quickHighlights as $i=>$highlight)<div class="quick__item"><span class="icon"><i class="{{ str_starts_with((string)($highlight['color']??''),'ri-')?$highlight['color']:($defaultHighlights[$i]['color']??'ri-star-line') }}"></i></span><div><h3>{{ $highlight['text'] }}</h3><p>{{ $highlight['description']??'' }}</p></div></div>@endforeach</div></div>
<section class="section white" id="about"><div class="shell about reveal"><div class="about__visual"><img class="about__image" src="{{ $aboutImage }}" alt="{{ $aboutImageAlt }}"><div class="quote">“{{ $aboutQuote }}”</div></div><div class="about__copy"><span class="eyebrow">{{ $aboutBadge }}</span><h2>{{ $aboutTitle }}</h2><div class="about__paragraphs">@foreach($aboutParagraphs as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div><div class="checks">@foreach(array_slice($aboutHighlights,0,4) as $highlight)<span><i class="ri-checkbox-circle-fill"></i>{{ $highlight['text'] }}</span>@endforeach</div><a class="btn btn--primary" href="#program">Program Unggulan</a></div></div></section>
@include('partials.pondok-identity-sections')
@php $leader=$teamMembers[0]??null;$leaderName=$leader['currentContent']['name']??'Ust. Arfandi Ismail';$leaderPosition=$leader['currentContent']['position']??'Pimpinan Pondok';$leaderPhoto=$mediaUrl($leader['profileImage']['url']??null);$leaderMessage=$leader['currentContent']['bio']??"Assalamu'alaikum warahmatullahi wabarakatuh. Selamat datang di Pondok Pesantren Al-Madinah Al-Kamilah. Kami hadir untuk membersamai para santri mencintai, menghafal, memahami, dan mengamalkan Al-Qur'an dalam kehidupan."; @endphp
<section class="section white" id="sambutan"><div class="shell welcome reveal"><div class="welcome__portrait">@if($leaderPhoto)<img src="{{ $leaderPhoto }}" alt="{{ $leaderName }}" loading="lazy">@else<div class="welcome__placeholder"><i class="ri-user-star-line"></i></div>@endif<div class="welcome__mark">“</div></div><div class="welcome__copy"><span class="eyebrow">Sambutan Ketua Pondok</span><h2>Menjaga Amanah, Menumbuhkan Generasi Al-Qur’an.</h2><blockquote>@if($leaderMessage)<p>{{ $leaderMessage }}</p>@else<p>Assalamu’alaikum warahmatullahi wabarakatuh.</p><p>Selamat datang di Pondok Pesantren Tahfidzul Qur’an Al-Madinatul Kamilah. Dengan penuh syukur, kami hadir untuk membersamai para santri mencintai, menghafal, memahami, dan mengamalkan Al-Qur’an dalam kehidupan.</p><p>Semoga ikhtiar pendidikan ini melahirkan generasi Qur’ani yang kokoh imannya, luas ilmunya, luhur adabnya, serta mampu memberi manfaat bagi keluarga, masyarakat, dan umat.</p><p>Wassalamu’alaikum warahmatullahi wabarakatuh.</p>@endif</blockquote><div class="welcome__signature"><span></span><div><strong>{{ $leaderName }}</strong><small>{{ $leaderPosition }}</small></div></div></div></div></section>
<section class="section soft program-section" id="program"><div class="shell"><div class="head reveal"><div><span class="eyebrow">Program Pendidikan</span><h2>Belajar, Menghafal, Bertumbuh.</h2></div><p>{{ $programIntro }}</p></div><div class="cards">@php($programs=!empty($services)?array_slice($services,0,6):$fallbackPrograms)@foreach($programs as $i=>$p)@php($fallbackProgram=$fallbackPrograms[$i%6])<article class="card reveal"><span class="card__num">0{{ $i+1 }}</span><span class="icon"><i class="{{ $p['icon']??$fallbackProgram[2] }}"></i></span><h3>{{ $p['title']??$fallbackProgram[0] }}</h3><p>{{ $p['description']??$fallbackProgram[1] }}</p><a href="{{ $wa }}" target="_blank" rel="noopener">Tanya program <i class="ri-whatsapp-line"></i></a></article>@endforeach</div></div></section>
<section class="stats"><div class="shell stats__grid reveal">@php($stats=!empty($about['statistics'])?array_slice($about['statistics'],0,4):(!empty($hero['stats'])?array_slice($hero['stats'],0,4):[['value'=>'30','suffixLabel'=>' Juz','label'=>'Target Hafalan'],['value'=>'24','suffixLabel'=>' Jam','label'=>'Lingkungan Qur’ani'],['value'=>'6','suffixLabel'=>' Program','label'=>'Pembinaan Terpadu'],['value'=>'100','suffixLabel'=>'%','label'=>'Komitmen Pendidikan']]))@foreach($stats as $s)<div class="stat"><strong>{{ $s['value']??0 }}{{ $s['suffixLabel']??'' }}</strong><span>{{ $s['label']??'Pencapaian' }}</span></div>@endforeach</div></section>
<section class="section white" id="gallery"><div class="shell"><div class="head reveal"><div><span class="eyebrow">Galeri Kegiatan</span><h2>Kehidupan di Pondok.</h2></div><p>Potret kegiatan belajar, ibadah, kebersamaan, dan proses tumbuh para santri bersama Al-Qur’an.</p></div><div class="gallery">@forelse(array_slice($galleryItems??[],0,5) as $item)@php($img=$mediaUrl($item['image']??null))<a class="gallery__item reveal" href="{{ route('landing.gallery.detail',['id'=>$item['_id']]) }}">@if($img)<img src="{{ $img }}" alt="{{ $item['title']??'Kegiatan santri' }}" loading="lazy">@else<div><i class="ri-image-line"></i></div>@endif<span class="label">{{ $item['title']??'Kegiatan Santri' }}</span></a>@empty @foreach(['Halaqah Tahfidz','Murajaah Bersama','Kajian Diniyah','Kebersamaan Santri','Kegiatan Pondok'] as $label)<div class="gallery__item reveal"><div><i class="ri-image-line"></i></div><span class="label">{{ $label }}</span></div>@endforeach @endforelse</div></div></section>
<section class="section soft" id="news"><div class="shell"><div class="head reveal"><div><span class="eyebrow">Kabar Pondok</span><h2>Informasi dan Cerita Terbaru.</h2></div><p>Ikuti kabar kegiatan, capaian santri, agenda pondok, dan artikel seputar pendidikan Al-Qur’an.</p></div><div class="news">@forelse(array_slice($news??[],0,3) as $article)@php($ni=$mediaUrl($article['featured_image']['url']??null))<article class="news__item reveal"><div class="news__media">@if($ni)<img src="{{ $ni }}" alt="{{ $article['featured_image']['alt']??$article['title'] }}" loading="lazy">@endif</div><div class="news__body"><span class="meta">{{ $article['category_id']['name']??'Kabar Pondok' }}{{ !empty($article['reading_time'])?' · '.$article['reading_time'].' menit':'' }}</span><h3>{{ $article['title'] }}</h3><p>{{ $article['excerpt']??'' }}</p><a class="more" href="{{ route('landing.news.detail',['id'=>$article['_id'],'slug'=>$article['slug']??null]) }}">Baca selengkapnya <i class="ri-arrow-right-line"></i></a></div></article>@empty @foreach([['Penerimaan Santri Baru','Informasi pendaftaran akan diumumkan melalui halaman ini.'],['Agenda Pondok','Ikuti kegiatan tahfidz, kajian, dan pembinaan santri.'],['Capaian Santri','Kabar perkembangan hafalan dan prestasi santri.']] as $n)<article class="news__item reveal"><div class="news__media"></div><div class="news__body"><span class="meta">Segera Hadir</span><h3>{{ $n[0] }}</h3><p>{{ $n[1] }}</p><a class="more" href="{{ $wa }}" target="_blank" rel="noopener">Hubungi admin <i class="ri-whatsapp-line"></i></a></div></article>@endforeach @endforelse</div><div class="news-more reveal"><a class="btn btn--primary" href="{{ route('landing.news.index') }}">Lihat Semua Berita <i class="ri-newspaper-line"></i></a></div></div></section>
<section class="cta" id="contact"><div class="shell cta__inner reveal"><div><span class="eyebrow" style="color:#e5c778">Mari Bertumbuh Bersama</span><h2>{{ $aboutCta['title']??'Siapkan langkah terbaik untuk perjalanan Qur’ani putra-putri Anda.' }}</h2><p>{{ $aboutCta['description']??'Hubungi pengelola pondok untuk informasi program, jadwal kunjungan, dan pendaftaran santri.' }}</p><p><i class="ri-map-pin-line"></i> {{ $address }}</p></div><div class="actions">@forelse($ctaButtons as $button)@php($ctaHref=$safeHeroLink($button['link']??null,$wa))<a class="btn btn--light" href="{{ $ctaHref }}" @if(str_starts_with($ctaHref,'http')) target="_blank" rel="noopener" @endif><i class="{{ $button['icon']??'ri-whatsapp-line' }}"></i> {{ $button['text']??'Hubungi Kami' }}</a>@empty<a class="btn btn--light" href="{{ $wa }}" target="_blank" rel="noopener"><i class="ri-whatsapp-line"></i> WhatsApp {{ $phone['displayNumber']??'+62 878-3163-3012' }}</a>@endforelse</div></div></section>
</main><footer class="footer"><div class="shell"><div class="footer__grid"><div><div class="footer__brand"><img src="{{ $logo }}" alt="Logo pondok"><h3>{{ $displayName }}</h3></div><p>Pendidikan tahfidz untuk membentuk generasi berilmu, beradab, dan bermanfaat.</p></div><div><h3>Navigasi</h3><div class="footer__links"><a href="#about">Profil Pondok</a><a href="#program">Program</a><a href="{{ route('landing.gallery.index') }}">Galeri</a><a href="{{ route('landing.news.index') }}">Kabar</a></div></div><div><h3>Hubungi Kami</h3><p>{{ $address }}</p><a href="{{ $wa }}" target="_blank" rel="noopener"><i class="ri-whatsapp-line"></i> +62 878-3163-3012</a>@if($email)<br><a href="mailto:{{ $email }}">{{ $email }}</a>@endif</div></div><div class="bottom"><span>© {{ date('Y') }} {{ $displayName }}.</span><span>Qur’an • Ilmu • Adab</span></div></div></footer>
@include('partials.murottal-player')@include('partials.floating-buttons',['floatingButtons'=>$floatingButtons??[]])@include('partials.active-popups',['activePopups'=>$activePopups??[]])
<script>
(()=>{
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const selector=['.hero__grid>div','.quick__item','.about>*','.head>*','.identity-layout>*','.identity-card','.welcome>*','.card','.stat','.gallery__item','.news__item','.cta__inner>*','.ppdb-layout>*'].join(',');
 const items=[...new Set([...document.querySelectorAll('.reveal'),...document.querySelectorAll(selector)])];
 const groups=['.quick__grid','.cards','.identity-grid','.stats__grid','.gallery','.news','.checks','.identity-mission ol','.ppdb-details'];
 items.forEach(el=>el.classList.add('reveal'));
 groups.forEach(group=>document.querySelectorAll(group).forEach(parent=>[...parent.children].forEach((child,index)=>{
   child.classList.add('reveal');
   child.style.setProperty('--reveal-delay',`${Math.min(index,7)*75}ms`);
 })));
 document.querySelectorAll('.about>*:first-child,.welcome>*:first-child,.identity-layout>*:first-child,.ppdb-layout>*:first-child').forEach(el=>el.dataset.reveal='left');
 document.querySelectorAll('.about>*:last-child,.welcome>*:last-child,.identity-layout>*:last-child,.ppdb-layout>*:last-child').forEach(el=>el.dataset.reveal='right');
 document.querySelectorAll('.card,.identity-card,.gallery__item,.news__item,.quick__item').forEach(el=>el.dataset.reveal='scale');
 document.documentElement.classList.add('motion-ready');
 const all=[...document.querySelectorAll('.reveal')];
 if(reduced||!('IntersectionObserver'in window)){
   all.forEach(el=>{el.classList.remove('reveal');el.classList.add('motion-revealed')});
   return;
 }
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{
   if(!entry.isIntersecting)return;
   const el=entry.target;
   el.classList.add('on');
   observer.unobserve(el);
   el.addEventListener('animationend',()=>{
     el.classList.remove('reveal','on');
     el.classList.add('motion-revealed');
     el.style.removeProperty('--reveal-delay');
   },{once:true});
 }),{threshold:.12,rootMargin:'0px 0px -10% 0px'});
 all.forEach(el=>observer.observe(el));
})();
</script></body></html>
