<aside class="murottal is-collapsed" data-murottal aria-label="Pemutar murotal Al-Qur'an">
    <button class="murottal__toggle" type="button" data-murottal-toggle aria-expanded="false">
        <i class="ri-headphone-line"></i><span>Murotal Al-Qur'an</span><i class="ri-arrow-down-s-line" data-murottal-chevron></i>
    </button>
    <div class="murottal__body" data-murottal-body>
        <div class="murottal__now"><span class="murottal__pulse" data-murottal-pulse></span><div><strong data-murottal-title>Memuat murotal...</strong><small data-murottal-status>Menyiapkan daftar qari dan surah</small></div></div>
        <label>Qari<select data-murottal-reciter aria-label="Pilih qari"><option>Memuat qari...</option></select></label>
        <label>Surah<select data-murottal-surah aria-label="Pilih surah"><option>Memuat surah...</option></select></label>
        <div class="murottal__controls">
            <button type="button" data-murottal-play aria-label="Putar murotal"><i class="ri-play-fill"></i></button>
            <label class="murottal__volume"><i class="ri-volume-up-line"></i><input data-murottal-volume type="range" min="0" max="1" step="0.05" value="0.65" aria-label="Volume murotal"></label>
        </div>
        <audio data-murottal-audio preload="auto" autoplay playsinline></audio>
    </div>
</aside>

<style>
.murottal{position:fixed;z-index:79;left:20px;bottom:20px;width:min(340px,calc(100vw - 40px));overflow:hidden;border:1px solid #d8af5766;border-radius:20px;background:rgba(255,255,255,.97);box-shadow:0 22px 55px #082a2230;backdrop-filter:blur(18px);color:var(--ink,#183a31)}.murottal__toggle{display:flex;width:100%;align-items:center;gap:9px;padding:14px 16px;border:0;background:linear-gradient(100deg,#123d32,#176548);color:#fff;font:700 .8rem var(--sans,'Plus Jakarta Sans',sans-serif);cursor:pointer}.murottal__toggle span{flex:1;text-align:left}.murottal__body{display:grid;gap:11px;padding:15px}.murottal.is-collapsed .murottal__body{display:none}.murottal.is-collapsed [data-murottal-chevron]{transform:rotate(180deg)}.murottal__now{display:flex;align-items:center;gap:10px}.murottal__now strong,.murottal__now small{display:block}.murottal__now strong{font:600 .88rem var(--serif,'Lora',serif);color:#123d32}.murottal__now small{color:#64786f;font-size:.66rem}.murottal__pulse{width:10px;height:10px;flex:0 0 10px;border-radius:50%;background:#aebdb6}.murottal.is-playing .murottal__pulse{background:#16855b;box-shadow:0 0 0 6px #16855b24;animation:murottal-pulse 1.4s infinite}.murottal label{display:grid;gap:4px;color:#64786f;font-size:.65rem;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.murottal select{width:100%;height:40px;padding:0 34px 0 11px;border:1px solid #dce7df;border-radius:11px;background:#fbf8ef;color:#183a31;font:600 .74rem var(--sans,'Plus Jakarta Sans',sans-serif)}.murottal__controls{display:flex;align-items:center;gap:13px}.murottal__controls>button{display:grid;width:42px;height:42px;flex:0 0 42px;place-items:center;border:0;border-radius:50%;background:#d8af57;color:#183a31;font-size:1.35rem;cursor:pointer}.murottal__volume{display:flex!important;flex:1!important;grid-template-columns:auto 1fr!important;align-items:center;gap:8px!important}.murottal__volume input{width:100%;accent-color:#16855b}@keyframes murottal-pulse{50%{box-shadow:0 0 0 10px #16855b08}}@media(max-width:575px){.murottal{left:14px;bottom:14px;width:calc(100vw - 84px)}.murottal:not(.is-collapsed){width:calc(100vw - 28px);z-index:90}}
</style>

<script>
document.addEventListener('DOMContentLoaded',()=>{
 const root=document.querySelector('[data-murottal]');if(!root)return;
 const audio=root.querySelector('[data-murottal-audio]'),reciter=root.querySelector('[data-murottal-reciter]'),surah=root.querySelector('[data-murottal-surah]'),play=root.querySelector('[data-murottal-play]'),volume=root.querySelector('[data-murottal-volume]'),title=root.querySelector('[data-murottal-title]'),status=root.querySelector('[data-murottal-status]'),toggle=root.querySelector('[data-murottal-toggle]');
 const store={get:(k,d)=>{try{return localStorage.getItem(k)??d}catch{return d}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{}}};let reciters=[],surahs=[],unlockArmed=false;
 const pad=n=>String(n).padStart(3,'0'),setPlaying=v=>{root.classList.toggle('is-playing',v);play.innerHTML=`<i class="ri-${v?'pause':'play'}-fill"></i>`;play.setAttribute('aria-label',v?'Jeda murotal':'Putar murotal')};
 const unlockEvents=['pointerdown','touchstart','keydown'];
 const disarmUnlock=()=>{unlockEvents.forEach(event=>document.removeEventListener(event,unlockPlayback,true));unlockArmed=false};
 const unlockPlayback=async()=>{if(!audio.src||!audio.paused)return disarmUnlock();try{await audio.play();disarmUnlock()}catch{}};
 const armUnlock=()=>{if(unlockArmed)return;unlockArmed=true;unlockEvents.forEach(event=>document.addEventListener(event,unlockPlayback,{capture:true,passive:true}));status.textContent='Murotal siap · mulai otomatis saat Anda menyentuh halaman'};
 const tryAutoplay=async()=>{audio.muted=false;try{await audio.play();disarmUnlock();return true}catch{setPlaying(false);armUnlock();return false}};
 const current=()=>reciters.find(r=>String(r.id)===reciter.value),loadTrack=async(autoplay=true)=>{const r=current(),s=surahs.find(x=>String(x.id)===surah.value);if(!r||!s)return;audio.src=`${r.server}${pad(s.id)}.mp3`;audio.load();title.textContent=`Surah ${s.name}`;status.textContent=r.name;store.set('pondokMurottalReciter',r.id);store.set('pondokMurottalSurah',s.id);if(autoplay)await tryAutoplay()};
 toggle.addEventListener('click',()=>{const collapsed=root.classList.toggle('is-collapsed');toggle.setAttribute('aria-expanded',String(!collapsed))});
 play.addEventListener('click',async()=>{if(audio.paused){try{await audio.play();disarmUnlock()}catch{status.textContent='Audio belum dapat diputar. Coba pilih qari lain.'}}else audio.pause()});audio.addEventListener('play',()=>setPlaying(true));audio.addEventListener('playing',()=>{setPlaying(true);disarmUnlock()});audio.addEventListener('pause',()=>setPlaying(false));audio.addEventListener('ended',()=>{const i=surahs.findIndex(x=>String(x.id)===surah.value);surah.value=String(surahs[(i+1)%surahs.length].id);loadTrack(true)});audio.addEventListener('error',()=>{setPlaying(false);status.textContent='Audio gagal dimuat. Silakan pilih qari lain.'});
 volume.value=store.get('pondokMurottalVolume','.65');audio.volume=Number(volume.value);volume.addEventListener('input',()=>{audio.volume=Number(volume.value);store.set('pondokMurottalVolume',volume.value)});reciter.addEventListener('change',()=>loadTrack(true));surah.addEventListener('change',()=>loadTrack(true));
 Promise.all([fetch('https://www.mp3quran.net/api/v3/reciters?language=id').then(r=>r.json()),fetch('https://www.mp3quran.net/api/v3/suwar?language=id').then(r=>r.json())]).then(([qr,qs])=>{surahs=qs.suwar||[];reciters=(qr.reciters||[]).flatMap(q=>(q.moshaf||[]).filter(m=>m.server&&m.surah_list).map(m=>({id:`${q.id}-${m.id}`,name:q.name,label:`${q.name} — ${m.name}`,server:m.server,surahs:m.surah_list.split(',').map(Number)}))).filter(r=>r.surahs.length===114);if(!reciters.length)throw new Error('Qari tidak tersedia');reciter.innerHTML=reciters.map(r=>`<option value="${r.id}">${r.label}</option>`).join('');surah.innerHTML=surahs.map(s=>`<option value="${s.id}">${s.id}. ${s.name}</option>`).join('');const savedR=store.get('pondokMurottalReciter',''),preferred=reciters.find(r=>/afasy|afasi|mishar|مشاري/i.test(r.name));reciter.value=reciters.some(r=>r.id===savedR)?savedR:(preferred?.id||reciters[0].id);surah.value='1';store.set('pondokMurottalSurah','1');loadTrack(true)}).catch(()=>{title.textContent='Murotal belum tersedia';status.textContent='Periksa koneksi internet lalu muat ulang halaman';reciter.innerHTML='<option>Gagal memuat qari</option>';surah.innerHTML='<option>Gagal memuat surah</option>'});
});
</script>
